package org.example.tahmiinbackend.league_matches;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@Data
@Builder
@AllArgsConstructor
@Entity
@Table
@JsonIgnoreProperties({"homeGoals","awayGoals","home_url","away_url","match_url","matches_completed_minimum","homeGoals_timings","awayGoals_timings","GoalCount_2hg","HTGoalCount","total_xg_prematch"})
public class LeagueMatches {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "league_matches_sequence")
    @SequenceGenerator(name = "league_matches_sequence", sequenceName = "league_matches_sequence", allocationSize = 1)
    private Long league_matches_id;
    private Long id;
    private Long homeID;
    private Long awayID;
    private String season;
    private String status;
    private Long roundID;
    private Integer game_week;
    private Integer revised_game_week;
    private Integer homeGoalCount;
    private Integer awayGoalCount;
    private Integer totalGoalCount;
    private Integer team_a_corners;
    private Integer team_b_corners;
    private Integer totalCornerCount;
    private Integer team_a_offsides;
    private Integer team_b_offsides;
    private Integer team_a_yellow_cards;
    private Integer team_b_yellow_cards;
    private Integer team_a_red_cards;
    private Integer team_b_red_cards;
    private Integer team_a_shotsOnTarget;
    private Integer team_b_shotsOnTarget;
    private Integer team_a_shotsOffTarget;
    private Integer team_b_shotsOffTarget;
    private Integer team_a_shots;
    private Integer team_b_shots;
    private Integer team_a_fouls;
    private Integer team_b_fouls;
    private Integer team_a_possession;
    private Integer team_b_possession;
    private Integer refereeID;
    private Integer coach_a_ID;
    private Integer coach_b_ID;
    private String stadium_name;
    private String stadium_location;
    private Integer team_a_cards_num;
    private Integer team_b_cards_num;
    private Double odds_ft_1;
    private Double odds_ft_x;
    private Double odds_ft_2;
    private Double odds_ft_over05;
    private Double odds_ft_over15;
    private Double odds_ft_over25;
    private Double odds_ft_over35;
    private Double odds_ft_over45;
    private Double odds_ft_under05;
    private Double odds_ft_under15;
    private Double odds_ft_under25;
    private Double odds_ft_under35;
    private Double odds_ft_under45;
    private Double odds_btts_yes;
    private Double odds_btts_no;
    private Double odds_team_a_cs_yes;
    private Double odds_team_a_cs_no;
    private Double odds_team_b_cs_yes;
    private Double odds_team_b_cs_no;
    private Double odds_doublechance_1x;
    private Double odds_doublechance_12;
    private Double odds_doublechance_x2;
    private Double odds_1st_half_result_1;
    private Double odds_1st_half_result_x;
    private Double odds_1st_half_result_2;
    private Double odds_2nd_half_result_1;
    private Double odds_2nd_half_result_x;
    private Double odds_2nd_half_result_2;
    private Double odds_dnb_1;
    private Double odds_dnb_2;
    private Double odds_corners_over_75;
    private Double odds_corners_over_85;
    private Double odds_corners_over_95;
    private Double odds_corners_over_105;
    private Double odds_corners_over_115;
    private Double odds_corners_under_75;
    private Double odds_corners_under_85;
    private Double odds_corners_under_95;
    private Double odds_corners_under_105;
    private Double odds_corners_under_115;
    private Double odds_corners_1;
    private Double odds_corners_x;
    private Double odds_corners_2;
    private Double odds_team_to_score_first_1;
    private Double odds_team_to_score_first_x;
    private Double odds_team_to_score_first_2;
    private Double odds_win_to_nil_1;
    private Double odds_win_to_nil_2;
    private Double odds_1st_half_over05;
    private Double odds_1st_half_over15;
    private Double odds_1st_half_over25;
    private Double odds_1st_half_over35;
    private Double odds_1st_half_under05;
    private Double odds_1st_half_under15;
    private Double odds_1st_half_under25;
    private Double odds_1st_half_under35;
    private Double odds_2nd_half_over05;
    private Double odds_2nd_half_over15;
    private Double odds_2nd_half_over25;
    private Double odds_2nd_half_over35;
    private Double odds_2nd_half_under05;
    private Double odds_2nd_half_under15;
    private Double odds_2nd_half_under25;
    private Double odds_2nd_half_under35;
    private Double odds_btts_1st_half_yes;
    private Double odds_btts_1st_half_no;
    private Double odds_btts_2nd_half_yes;
    private Double odds_btts_2nd_half_no;
    private Integer overallGoalCount;
    private Integer ht_goals_team_a;
    private Integer ht_goals_team_b;
    private Integer goals_2hg_team_a;
    private Integer goals_2hg_team_b;
    private Integer date_unix;
    private Integer winningTeam;
    private Integer no_home_away;
    private Integer btts_potential;
    private Integer btts_fhg_potential;
    private Integer btts_2hg_potential;
    private Integer goalTimingDisabled;
    private Integer attendance;
    private Integer corner_timings_recorded;
    private Integer card_timings_recorded;
    private Integer team_a_fh_corners;
    private Integer team_b_fh_corners;
    private Integer team_a_2h_corners;
    private Integer team_b_2h_corners;
    private Integer corner_fh_count;
    private Integer corner_2h_count;
    private Integer team_a_fh_cards;
    private Integer team_b_fh_cards;
    private Integer team_a_2h_cards;
    private Integer team_b_2h_cards;
    private Integer total_fh_cards;
    private Integer total_2h_cards;
    private Integer attacks_recorded;
    private Integer team_a_dangerous_attacks;
    private Integer team_b_dangerous_attacks;
    private Integer team_a_attacks;
    private Integer team_b_attacks;
    private Double team_a_xg;
    private Double team_b_xg;
    private Double total_xg;
    private Integer team_a_penalties_won;
    private Integer team_b_penalties_won;
    private Integer team_a_penalty_goals;
    private Integer team_b_penalty_goals;
    private Integer team_a_penalty_missed;
    private Integer team_b_penalty_missed;
    private Integer pens_recorded;
    private Integer goal_timings_recorded;
    private Integer team_a_0_10_min_goals;
    private Integer team_b_0_10_min_goals;
    private Integer team_a_corners_0_10_min;
    private Integer team_b_corners_0_10_min;
    private Integer team_a_cards_0_10_min;
    private Integer team_b_cards_0_10_min;
    private Integer throwins_recorded;
    private Integer team_a_throwins;
    private Integer team_b_throwins;
    private Integer freekicks_recorded;
    private Integer team_a_freekicks;
    private Integer team_b_freekicks;
    private Integer goalkicks_recorded;
    private Integer team_a_goalkicks;
    private Integer team_b_goalkicks;
    private Integer o45_potential;
    private Integer o35_potential;
    private Integer o25_potential;
    private Integer o15_potential;
    private Integer o05_potential;
    private Integer o15HT_potential;
    private Integer o05HT_potential;
    private Integer o05_2H_potential;
    private Integer o15_2H_potential;
    private Integer corners_potential;
    private Integer offsides_potential;
    private Integer cards_potential;
    private Integer avg_potential;
    private String home_image;
    private String home_name;
    private String away_image;
    private String away_name;
    private Double home_ppg;
    private Double away_ppg;
    private Double pre_match_home_ppg;
    private Double pre_match_away_ppg;
    private Double pre_match_teamA_overall_ppg;
    private Double pre_match_teamB_overall_ppg;
    private Integer u45_potential;
    private Integer u35_potential;
    private Integer u25_potential;
    private Integer u15_potential;
    private Integer u05_potential;
    private Integer corners_o85_potential;
    private Integer corners_o95_potential;
    private Integer corners_o105_potential;
    private Double team_a_xg_prematch;
    private Double team_b_xg_prematch;
    private Long competition_id;
    private Boolean over05;
    private Boolean over15;
    private Boolean over25;
    private Boolean over35;
    private Boolean over45;
    private Boolean over55;
    private Boolean btts;

    public LeagueMatches() {
    }


}
